name: Publish Snapshot

on:
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.filter.outputs.core }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            core:
              - '.github/workflows/**'
              - 'core/**'
              - '*gradle*'
              - 'set-version.sh'

  build:
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Grant execute permission to scripts
        run: |
          chmod +x gradlew
          chmod +x set-version.sh
      - name: Set version
        id: semver
        run: ./set-version.sh -t minor
      - name: Publish snapshot for next minor release
        run: VERSION=${{ steps.semver.outputs.SEMVER }} make snapshot-minor
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPEUSERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPEPASSWORD }}
